name: Insurance Risk Analytics CI/CD

on:
  push:
    branches: 
      - main
      - task-*
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:


    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install flake8 pytest nbconvert papermill dvc


    - name: Run flake8 (linting)
      run: |
        flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 src --count --exit-zero --max-complexity=12 --max-line-length=120 --statistics

    - name: Run tests
      run: |
        pytest -q || true  # allow passing if no tests created yet


    - name: Execute EDA notebook
      run: |
        papermill notebooks/01_eda.ipynb notebooks/_executed_01_eda.ipynb --log-output || true


    - name: Configure DVC
      run: |
        dvc init -f
        dvc remote add -d localremote ./dvcstore
        dvc pull || true

    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: analytics-artifacts
        path: |
          data/interim/cleaned.csv
          notebooks/_executed_01_eda.ipynb
          dvc.lock
          dvc.yaml
        if-no-files-found: ignore
